'use strict'
// 可选开发验证：传入 Playwright 模块路径，无需为普通使用者安装依赖。
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const path = require('node:path')
const { pathToFileURL } = require('node:url')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const output = path.resolve(__dirname, '../artifacts')
async function run() {
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, deviceScaleFactor: 1 })
    const page = await context.newPage()
    const errors = []
    page.on('pageerror', (error) => errors.push(error.message))
    const url = pathToFileURL(path.resolve(__dirname, '../index.html')).href
    let count = 0
    async function check(name, action) { await action(); count++; console.log(`PASS ${name}`) }
    await page.goto(url)
    assert.ok(!(await page.locator('.site-footer').textContent()).includes('本地版本'))
    assert.ok(!(await page.locator('.site-footer').textContent()).includes('当前浏览器'))
    await check('file:// 直接打开与首屏示例', async () => { await page.locator('.card').first().waitFor(); assert.equal(await page.locator('.card').count(), 5); assert.ok((await page.locator('h1').textContent()).includes('让遗失有回音')); await page.screenshot({ path: path.join(output, 'desktop-home.png'), fullPage: true }) })
    await check('搜索名称、地点与清空筛选', async () => { await page.getByRole('searchbox').fill('图书馆'); assert.equal(await page.locator('.card').count(), 1); await page.getByRole('searchbox').fill('不存在的物品'); assert.equal(await page.locator('.card').count(), 0); await page.getByRole('button', { name: '清除筛选' }).click(); assert.equal(await page.locator('.card').count(), 5) })
    await check('类型、分类与完成状态筛选', async () => { await page.getByRole('button', { name: '失物招领', exact: true }).click(); assert.equal(await page.locator('.card').count(), 3); await page.getByRole('button', { name: '证件钥匙', exact: true }).click(); assert.equal(await page.locator('.card').count(), 1); await page.getByRole('button', { name: '全部', exact: true }).click(); await page.locator('#status-select').selectOption('closed'); assert.equal(await page.locator('.card').count(), 1); await page.getByRole('button', { name: '全部信息' }).click(); await page.locator('#status-select').selectOption('open') })
    await check('他人示例仅可联系而不可管理', async () => { await page.getByRole('link', { name: '查看白色无线耳机详情' }).click(); await page.getByRole('button', { name: '查看联系方式' }).click(); assert.ok((await page.locator('#contact-value').inputValue()).includes('demo_')); assert.equal(await page.getByRole('button', { name: '删除信息', exact: true }).count(), 0) })
    await check('复制受限时提供手动复制回退', async () => { await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { value: undefined, configurable: true })); await page.locator('#copy-contact').click(); assert.ok((await page.locator('#toast').textContent()).includes('Ctrl+C')); assert.equal(await page.locator('#contact-value').evaluate((input) => input.selectionEnd - input.selectionStart), (await page.locator('#contact-value').inputValue()).length); await page.locator('[data-close="contact-dialog"]').click() })
    await page.getByRole('link', { name: '＋ 发布信息', exact: true }).click()
    await check('草稿切页和刷新恢复', async () => { await page.locator('[name="title"]').fill('黑色键盘'); await page.getByRole('link', { name: '寻物广场', exact: true }).click(); await page.getByRole('link', { name: '＋ 发布信息', exact: true }).click(); assert.equal(await page.locator('[name="title"]').inputValue(), '黑色键盘'); await page.reload(); assert.equal(await page.locator('[name="title"]').inputValue(), '黑色键盘') })
    await page.locator('[name="location"]').fill('测试图书馆 A201')
    await page.locator('textarea[name="description"]').fill('黑色机械键盘，背面有黄色贴纸。')
    await page.locator('[name="contact"]').fill('微信：test_web_2026')
    await page.locator('[name="date"]').fill(new Date().toLocaleDateString('sv-SE'))
    await check('不支持的图片明确拒绝', async () => { await page.locator('#photo-input').setInputFiles({ name: 'unsafe.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg/>') }); assert.ok((await page.locator('#publish-error').textContent()).includes('请选择')) })
    await check('真实照片压缩与发布昵称流程', async () => {
      const image = await page.locator('.brand img').screenshot()
      await page.locator('#photo-input').setInputFiles({ name: 'test.png', mimeType: 'image/png', buffer: image })
      await page.locator('#photo-preview img').waitFor()
      await page.locator('#publish-submit').click()
      await page.locator('#nickname-dialog[open]').waitFor()
      await page.locator('#nickname-input').fill('网页测试同学')
      await page.getByRole('button', { name: '保存昵称', exact: true }).click()
      await page.getByRole('heading', { name: '黑色键盘', exact: true }).waitFor()
      assert.equal(await page.locator('.detail-visual img').count(), 1)
      assert.equal(await page.locator('.detail-content > .badge').first().textContent(), '寻物中')
      assert.equal(await page.locator('.detail-content .local-note').count(), 0)
      assert.ok(!(await page.locator('.detail-content').textContent()).includes('只有你主动更新'))
      await page.screenshot({ path: path.join(output, 'desktop-detail.png'), fullPage: true })
    })
    await check('刷新后物品及照片仍可读取', async () => { await page.reload(); await page.getByRole('heading', { name: '黑色键盘', exact: true }).waitFor(); assert.ok(await page.locator('.detail-visual img').evaluate((image) => image.complete && image.naturalWidth > 0)); assert.equal(await page.locator('#nickname-button').textContent(), '◉ 网页测试同学') })
    await check('状态确认可取消、完成、重新开启', async () => { await page.getByRole('button', { name: '标记已找回', exact: true }).click(); await page.locator('[data-close="confirm-dialog"]').click(); assert.equal(await page.locator('.detail-content > .badge').first().textContent(), '寻物中'); await page.getByRole('button', { name: '标记已找回', exact: true }).click(); await page.locator('#confirm-action').click(); assert.equal(await page.locator('.detail-content > .badge').first().textContent(), '已找回'); await page.getByRole('button', { name: '重新开启', exact: true }).click(); await page.locator('#confirm-action').click(); assert.equal(await page.locator('.detail-content > .badge').first().textContent(), '寻物中') })
    await check('删除确认与我的发布更新', async () => { await page.getByRole('button', { name: '删除信息', exact: true }).click(); await page.locator('[data-close="confirm-dialog"]').click(); assert.equal(await page.getByRole('heading', { name: '黑色键盘', exact: true }).count(), 1); await page.getByRole('button', { name: '删除信息', exact: true }).click(); await page.locator('#confirm-action').click(); await page.getByRole('heading', { name: '还没有发布记录', exact: true }).waitFor() })
    await check('缺失详情展示错误而非跳转其他物品', async () => { await page.goto(url + '#detail?id=missing'); await page.getByRole('heading', { name: '这条信息不存在或已删除' }).waitFor(); assert.equal(await page.locator('.detail-layout').count(), 0) })
    await check('输入 HTML 只显示文本，不执行脚本', async () => {
      await page.goto(url + '#publish?type=found')
      await page.locator('[name="title"]').fill('<img onerror=alert(1)>')
      await page.locator('[name="location"]').fill('<script>alert(1)</script>')
      await page.locator('textarea[name="description"]').fill('<svg onload=alert(1)> 特殊字符仅作为文本。')
      await page.locator('[name="contact"]').fill('test')
      await page.locator('#publish-submit').click()
      await page.getByRole('heading', { name: '<img onerror=alert(1)>', exact: true }).waitFor()
      assert.equal(await page.locator('main script, main svg, main img[onerror]').count(), 0)
    })
    await check('取消昵称设置不会误发布', async () => {
      await page.evaluate(() => { const state = JSON.parse(localStorage.getItem('shiguang_web_v1')); state.nickname = ''; localStorage.setItem('shiguang_web_v1', JSON.stringify(state)) })
      await page.goto(url + '#publish'); await page.locator('[name="title"]').fill('取消发布测试'); await page.locator('[name="location"]').fill('图书馆'); await page.locator('textarea[name="description"]').fill('用于测试取消设置昵称的场景'); await page.locator('[name="contact"]').fill('test'); await page.locator('#publish-submit').click(); await page.locator('#nickname-dialog[open]').waitFor(); await page.locator('[data-close="nickname-dialog"]').click(); assert.ok(page.url().includes('#publish')); assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('shiguang_web_v1')).items.filter((item) => item.title === '取消发布测试').length), 0)
    })
    await check('未来日期被浏览器阻止，数据不变', async () => { const before = await page.evaluate(() => localStorage.getItem('shiguang_web_v1')); await page.locator('[name="date"]').fill('2099-12-31'); await page.locator('#publish-submit').click(); assert.equal(await page.locator('[name="date"]').evaluate((input) => input.validity.rangeOverflow), true); assert.equal(await page.evaluate(() => localStorage.getItem('shiguang_web_v1')), before); await page.locator('[name="date"]').fill(new Date().toLocaleDateString('sv-SE')) })
    await check('必填字段空白不能发布', async () => { await page.locator('[name="title"]').fill('  '); await page.locator('#publish-submit').click(); assert.ok((await page.locator('#publish-error').textContent()).includes('请填写')); await page.locator('[name="title"]').fill('取消发布测试') })
    await check('普通模式与独立浏览器上下文数据隔离', async () => { const other = await browser.newContext(); const otherPage = await other.newPage(); await otherPage.goto(url + '#mine'); await otherPage.getByRole('heading', { name: '还没有发布记录' }).waitFor(); assert.equal(await otherPage.locator('#nickname-button').textContent(), '设置昵称'); await other.close() })
    await check('移动端布局无横向溢出', async () => { await page.setViewportSize({ width: 390, height: 844 }); await page.goto(url + '#home'); await page.locator('.card').first().waitFor(); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); await page.screenshot({ path: path.join(output, 'mobile-home.png'), fullPage: true }); await page.goto(url + '#publish'); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); await page.screenshot({ path: path.join(output, 'mobile-publish.png'), fullPage: true }) })
    await check('禁用存储时展示提示而非白屏', async () => { const blocked = await browser.newContext(); await blocked.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new Error('disabled') }, configurable: true })); const blockedPage = await blocked.newPage(); await blockedPage.goto(url); await blockedPage.getByRole('heading', { name: '暂时无法读取数据' }).waitFor(); assert.ok((await blockedPage.locator('main').textContent()).includes('普通模式')); await blocked.close() })
    await check('控制台没有未处理页面异常', async () => assert.deepEqual(errors, []))
    console.log(`Chrome ${browser.version()}：${count} 组端到端检查通过（直接打开 HTML，无服务器）。`)
    await context.close()
  } finally { await browser.close() }
}
run().catch((error) => { console.error(error); process.exitCode = 1 })
